services:
  mongo:
    image: mongo:7
    container_name: placementor-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    environment:
      MONGO_INITDB_DATABASE: placementor

    networks:
      - placementor-network

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16-alpine
    container_name: placementor-postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: placementor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - placementor-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d placementor"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    container_name: placementor-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: ["redis-server", "--appendonly", "yes"]

    networks:
      - placementor-network

  backend:
    image: souravkumar09/placementor-backend:latest
    container_name: placementor-backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      NODE_ENV: production
      PORT: 5000

      # Mongo
      MONGOURL: mongodb://mongo:27017/placementor

      # Frontend URLs
      CLIENT_URL: http://localhost:3000
      FRONTEND_URL: http://localhost:3000

      # Backend URL
      BASE_URL: http://localhost:5000

      # Redis
      REDIS_URL: redis://redis:6379

      # PostgreSQL
      PAYMENTS_PG_ENABLED: "true"
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: placementor
      PGUSER: postgres
      PGPASSWORD: postgres

    depends_on:
      mongo:
        condition: service_healthy

      redis:
        condition: service_started

      postgres:
        condition: service_healthy

    volumes:
      - backend_uploads:/app/uploads

    networks:
      - placementor-network

  frontend:
    image: souravkumar09/placementor-frontend:latest
    container_name: placementor-frontend
    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - placementor-network

networks:
  placementor-network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
  backend_uploads:
  redis_data: